Repository slint-ui/slint, pull requests merged in 2023-07, with the labels that each got.

#3046 Attempt to fix a panic in accesskit
  internal/backends/winit/accesskit.rs
Labels: accessibility

#3077 Fix setting rotation-angle and opacity from a callback
  internal/compiler/generator/rust.rs
  internal/compiler/passes/lower_property_to_element.rs
  tests/screenshots/cases/software/basic/linear-gradients.slint
Labels: candidate-for-bugfix-release

#3086 Remove the Cargo.lock and pin deps in CI instead
  .github/workflows/ci.yaml
  Cargo.lock
Labels: a:ci

#3098 Fix disapearing debugging techniques docs from C++ docs
  api/cpp/docs/index.rst
  xtask/src/cppdocs.rs
Labels: a:documentation

#3082 add row-pointer-event callback to tableview
  docs/language/src/builtins/widgets.md
  internal/compiler/widgets/fluent-base/tableview.slint
  internal/compiler/widgets/material-base/tableview.slint
  internal/compiler/widgets/native/std-widgets.slint
Labels: a:widgets

#3165 Added item-pointer-event to StdListView
  CHANGELOG.md
  docs/language/src/builtins/widgets.md
  internal/compiler/widgets/fluent-base/components.slint
  internal/compiler/widgets/fluent-base/listview.slint
  internal/compiler/widgets/material-base/components.slint
  internal/compiler/widgets/material-base/listview.slint
  internal/compiler/widgets/native/std-widgets.slint
Labels: a:widgets
