Repository slint-ui/slint, pull requests merged in 2023-09, with the labels that each got.

#3442 Add documentation about the different renderers, their pros/const, and availability in backends and API
  api/cpp/docs/cmake.md
  api/rs/slint/docs.rs
  docs/reference/index.rst
  docs/reference/src/advanced/backends.md
  docs/reference/src/advanced/backends_and_renderers.md
Labels: a:documentation, candidate-for-bugfix-release

#3462 Finish state visuals of cupertino style.
  internal/compiler/widgets/cupertino-base/button.slint
  internal/compiler/widgets/cupertino-base/checkbox.slint
  internal/compiler/widgets/cupertino-base/combobox.slint
  internal/compiler/widgets/cupertino-base/components.slint
  internal/compiler/widgets/cupertino-base/groupbox.slint
  internal/compiler/widgets/cupertino-base/lineedit.slint
  internal/compiler/widgets/cupertino-base/listview.slint
  internal/compiler/widgets/cupertino-base/progressindicator.slint
  internal/compiler/widgets/cupertino-base/scrollview.slint
  internal/compiler/widgets/cupertino-base/slider.slint
  internal/compiler/widgets/cupertino-base/spinbox.slint
  internal/compiler/widgets/cupertino-base/std-widgets-impl.slint
  internal/compiler/widgets/cupertino-base/styling.slint
  internal/compiler/widgets/cupertino-base/switch.slint
  internal/compiler/widgets/cupertino-base/tableview.slint
  internal/compiler/widgets/cupertino-base/tabwidget.slint
  internal/compiler/widgets/cupertino-base/textedit.slint
  internal/compiler/widgets/material-base/listview.slint
Labels: a:widgets

#3471 compiler: Fix loading the same file twice would result in infinite pending state
  internal/compiler/typeloader.rs
Labels: candidate-for-bugfix-release

#3473 Don't panic when the windowing system tries to assign a zero size to a GL surface
  CHANGELOG.md
  internal/renderers/skia/opengl_surface.rs
Labels: candidate-for-bugfix-release

#3487 FemtoVG: fix eliding empty lines
  internal/renderers/femtovg/fonts.rs
Labels: candidate-for-bugfix-release

#3490 Skia: fix eliding of multiline text
  internal/renderers/skia/itemrenderer.rs
  internal/renderers/skia/lib.rs
  internal/renderers/skia/textlayout.rs
Labels: candidate-for-bugfix-release

#3488 FemtoVG: fix vertical alignment of elided text
  internal/renderers/femtovg/fonts.rs
Labels: candidate-for-bugfix-release

#3498 Hide the ComponentFactory from the docs
  api/rs/slint/lib.rs
Labels: candidate-for-bugfix-release

#3495 StandardTableView: prevent internal FocusScope from eating the first press
  internal/compiler/widgets/cupertino-base/tableview.slint
  internal/compiler/widgets/fluent-base/tableview.slint
  internal/compiler/widgets/material-base/tableview.slint
  internal/compiler/widgets/native/tableview.slint
Labels: a:widgets

#3518 Fix compiler panic with popup.closes
  internal/compiler/llr/lower_expression.rs
  tests/cases/elements/popupwindow_close.slint
Labels: candidate-for-bugfix-release

#3542 Qt style: Fix GroupBox not being clipped
  CHANGELOG.md
  internal/backends/qt/qt_widgets.rs
  internal/backends/qt/qt_widgets/listviewitem.rs
  internal/backends/qt/qt_widgets/tableheadersection.rs
Labels: candidate-for-bugfix-release

#3564 Unpin winit version
  internal/backends/winit/Cargo.toml
Labels: candidate-for-bugfix-release

#3493 Added Model implementation for napi
  api/napi/.gitignore
  api/napi/__test__/js_value_conversion.spec.ts
  api/napi/__test__/types.spec.ts
  api/napi/index.d.ts
  api/napi/index.ts
  api/napi/package.json
  api/napi/src/interpreter/component_instance.rs
  api/napi/src/interpreter/value.rs
  api/napi/src/types/model.rs
Labels: a:language-javascript

#3569 Remove the preview from the rust docs
  .github/workflows/build_docs.yaml
  api/rs/slint/Cargo.toml
Labels: candidate-for-bugfix-release

#3570 Fix cross-compilation with a Yocto SDK
  api/cpp/CMakeLists.txt
Labels: candidate-for-bugfix-release

#3572 doc: Attempt to document the algorithm by which the Flickable interpr…
  docs/reference/src/language/builtins/elements.md
Labels: a:documentation, candidate-for-bugfix-release
