Repository slint-ui/slint, pull requests merged in 2023-08, with the labels that each got.

#3171 Initial setup for napi-rs port
  .github/workflows/ci.yaml
  .gitignore
  .reuse/dep5
  Cargo.toml
  api/napi/.gitignore
  api/napi/.npmignore
  api/napi/.yarnrc.yml
  api/napi/Cargo.toml
  api/napi/README.md
  api/napi/__test__/copiler.spec.ts
  api/napi/__test__/js_value_conversion.spec.ts
  api/napi/__test__/resources/rgb.png
  api/napi/__test__/types.spec.ts
  api/napi/build.rs
  api/napi/npm/darwin-arm64/README.md
  api/napi/npm/darwin-arm64/package.json
  api/napi/npm/darwin-x64/README.md
  api/napi/npm/darwin-x64/package.json
  api/napi/npm/linux-arm-gnueabihf/README.md
  api/napi/npm/linux-arm-gnueabihf/package.json
  api/napi/npm/linux-arm64-gnu/README.md
  api/napi/npm/linux-arm64-gnu/package.json
  api/napi/npm/linux-x64-gnu/README.md
  api/napi/npm/linux-x64-gnu/package.json
  api/napi/npm/win32-arm64-msvc/README.md
  api/napi/npm/win32-arm64-msvc/package.json
  api/napi/npm/win32-ia32-msvc/README.md
  api/napi/npm/win32-ia32-msvc/package.json
  api/napi/npm/win32-x64-msvc/README.md
  api/napi/npm/win32-x64-msvc/package.json
  api/napi/package.json
  api/napi/src/interpreter.rs
  api/napi/src/interpreter/component_compiler.rs
  api/napi/src/interpreter/component_definition.rs
  api/napi/src/interpreter/component_instance.rs
  api/napi/src/interpreter/diagnostic.rs
  api/napi/src/interpreter/value.rs
  api/napi/src/lib.rs
  api/napi/src/types.rs
  api/napi/src/types/brush.rs
  api/napi/src/types/image_data.rs
  api/napi/src/types/model.rs
Labels: a:language-javascript

#3233 Fix slint-lsp process zombies
  CHANGELOG.md
  tools/lsp/main.rs
Labels: candidate-for-bugfix-release

#3240 doc: Add links to VS Code and our extension
  docs/language/index.rst
Labels: a:documentation, candidate-for-bugfix-release

#3242 Begin documenting supported (target) platforms
  docs/reference/index.rst
  docs/reference/src/introduction/supported_platforms.md
Labels: a:documentation
